
stages:
  - build

bitstream:
  stage: build
  image: vivado2018:2018.3
  script:
    - env
    - /opt/Xilinx/Vivado/2018.3/bin/vivado -mode tcl -source xilinx/NaiveMIPS/build.tcl xilinx/NaiveMIPS/PrjVivao.xpr

  artifacts:
    paths:
      - xilinx/NaiveMIPS/PrjVivao.runs/impl_1/soc_toplevel.bit

